name: push_to_docker

on:
  push:
    tags:
      - build_docker_*

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push with whisper
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: yanyaobbb/bilibili_gpt_helper:with_whisper
          target: with_whisper
      - name: Build and push without whisper
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: yanyaobbb/bilibili_gpt_helper:latest
          target: without_whisper
