name: release_docker
run-name: Release V${{ github.event.inputs.version }} docker image

on:
  workflow_dispatch:
    inputs:
      version:
        description: '版本'
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push with whisper
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/bilibili_gpt_helper:with_whisper
            ${{ secrets.DOCKERHUB_USERNAME }}/bilibili_gpt_helper:${{ github.event.inputs.version }}_whisper
          target: with_whisper
          file: ./ci/Dockerfile

      - name: Build and push without whisper
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/bilibili_gpt_helper:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/bilibili_gpt_helper:${{ github.event.inputs.version }}
          target: without_whisper
          file: ./ci/Dockerfile